services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.environment/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build:
      context: .
      dockerfile: .environment/local/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=logger"
    volumes:
      - ./:/app
      - ./.environment/local/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    image: postgres:16.4-alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=logger
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"